/*
    SPDX-FileCopyrightText: 2026 Milian Wolff <mail@milianw.de>

    SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
*/

#pragma once

#cmakedefine01 PLASMA_KEYBOARD_SOUNDS_ENABLED
#cmakedefine01 PLASMA_KEYBOARD_VIBRATION_ENABLED
#cmakedefine01 PLASMA_KEYBOARD_LIBPINYIN_ENABLED
#cmakedefine01 PLASMA_KEYBOARD_LIBCHEWING_ENABLED
#cmakedefine01 PLASMA_KEYBOARD_LIBHANGUL_ENABLED
#cmakedefine01 PLASMA_KEYBOARD_ANTHY_ENABLED

#define PLASMA_KEYBOARD_LIBPINYIN_SYSTEM_DIR "@PLASMA_KEYBOARD_LIBPINYIN_SYSTEM_DIR@"
#define PLASMA_KEYBOARD_LIBCHEWING_DATADIR "@PLASMA_KEYBOARD_LIBCHEWING_DATADIR@"
